// Top-level routes that must NOT have a locale prefix.
// OAuth callback URIs are registered with Google/GitHub as fixed URLs.
// Password reset link is generated by the backend without a locale prefix.
export const authRoutes = [
  {
    path: '/auth/:provider/callback',
    name: 'oauth-callback',
    component: () => import('../pages/auth/OAuthCallback.vue'),
    meta: { layout: 'auth' },
  },
  {
    path: '/reset-password',
    name: 'reset-password',
    component: () => import('../pages/auth/ResetPassword.vue'),
    meta: { layout: 'auth' },
  },
  {
    path: '/verify-email',
    name: 'verify-email',
    component: () => import('../pages/auth/VerifyEmail.vue'),
    meta: { bare: true },
  },
]
